### ISSUE TITLE
EmailSnooze and maxEmailsPerDay precedence

### ISSUE THREAD

**Issue by eydun** [AppsDevTeam/error-logger#12]
I am not sure I fully understand. 

How does emailSnooze work in combination with maxEmailsPerDay?

Thanks.

**Comment by thorewi** [comment]
Hi there,

thank you for your comment... The implementation wasn't quite right, but it should be fixed now.

EmailSnooze was taken from default Nette error logger (where is set to 2 day)... if you set emailSnooze to 1 minute for example, you may get the same error every single minute (if it occurs in your project), but at most $maxEmailPerDay times per day... to avoid be spammed to much...

**Comment by thorewi** [comment]
thank you... if you like the logger, you can add a star :)

**Comment by thorewi** [comment]
hopefully it will be ok now...
